### ISSUE TITLE
cannot get it to run, without failure

### ISSUE THREAD

**Issue by gadget78** [nmaggioni/r710-fan-controller#15]
cannot get it to run, without failure, so i have made sure dependencies are installed,
i CAN run `sensors` on command line, and i get the CPU temps listed... 
when i check with `systemctl status fan-control.service`
i get an error of;
`Process: 157776 ExecStart=/opt/fan_control/venv/bin/python3 -u /opt/fan_control/fan_control.py (code=exited,status=1/FAILURE)`

if i try to run just the fan_control.py on its own from command line i get;
`root@pve2:/opt/fan_control# python3 fan_control.py
Traceback (most recent call last):
  File "/opt/fan_control/fan_control.py", line 7, in <module>
    import sensors  # https://github.com/bastienleonard/pysensors.git
    ModuleNotFoundError: No module named 'sensors'`
i have made sure that `libsensors4-dev` is installed as well...

this is under ProxMox version 8.0.9

**Comment by gadget78** [comment]
well im not sure what i actually did.. 
messed with https://github.com/bastienleonard/pysensors
trying to install it, which failed, but i think maybe installing some other python base like pip may of fixed it?

even tho its now running i think iDrac keeps stealing control ? as they keep increasing when temp. are the same using sensors command..

**Comment by nmaggioni** [comment]
Please post the full output of the script after you managed to get it running and the exact hardware model you are running it on. If iDRAC is still controlling the fans it probably means that either it is not receving the commands or they are not compatible with your version.
