### ISSUE TITLE
Fan control should be reset to "automatic" when script receives SIGTERM

### ISSUE THREAD

**Issue by FlorianZ** [nmaggioni/r710-fan-controller#5]
Currently, when stopping the systemd service fan control remains in whatever mode the script was last in. If this is "manual" mode, and the fans are running at at low RPM, CPU temperatures may reach critical levels during boot / inside BIOS, where low-power states are not maintained. The script should probably make a best effort to return to "automatic" mode when it exits.

I can submit a PR when I get a chance, just logging this for the time being. Thank you!

**Comment by nmaggioni** [comment]
Good idea, may be useful in some setups even though I don't see it working reliably 100% of the time unfortunately: if the script is stopping, chances are that the main or remote systems are already halting and thus might not behave as expected.

In absence of PRs I might implement this soon anyway, thanks for the heads up.
