### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by RarogCmex** [nmaggioni/r710-fan-controller#7]
Python 3.7 is end of life (with bugfix released) in mid 2023. Many rolling-release distributions (and my Gentoo) will drop it earlier however. So I ask to port that script to latest python 3.9.

**Comment by nmaggioni** [comment]
Everything works fine here on `Python 3.9.1`. If you have encountered difficulties on your system, please provide a traceback.

**Comment by RarogCmex** [comment]
Thank you for aswer!
